[functions.ai-generate]
verify_jwt = true
entrypoint = "./functions/ai-generate/index.ts"

[functions.payment-checkout]
verify_jwt = true
entrypoint = "./functions/payment-checkout/index.ts"

[functions.designly-agent]
verify_jwt = true
entrypoint = "./functions/designly-agent/index.ts"

[functions.admin-gift]
verify_jwt = true
entrypoint = "./functions/admin-gift/index.ts"

[functions.music-generate]
verify_jwt = true
entrypoint = "./functions/music-generate/index.ts"
